<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Nexus.Pos.Launcher</AssemblyName>
    <RootNamespace>Nexus.Pos.Launcher</RootNamespace>
    <Product>Nexus POS</Product>
    <Company>Nexus</Company>
    <Authors>www.ecaturonald.tech</Authors>
    <Copyright>Copyright © 2026 Nexus</Copyright>
    <Version>4.0.0</Version>
    <FileVersion>4.0.0.0</FileVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
</Project>
